version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    ports: 
      - "3000:3000"

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3001:80"

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./server:/app
    ports: 
      - "8080:8080"
    environment:
      PORT: ${PORT}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_HOST: ${MONGO_HOST}
